import {
  User,
  Vehicle,
  ChargingStation,
  Charger,
  StationPrice,
  QueueEntry,
  StationDemand,
  Reservation,
  FaultReport,
  Notification,
  StationSyncLog,
} from "../types";

export const initialUsers: User[] = [
  {
    id: "usr_admin_01",
    name: "System Administrator",
    email: "admin@voltwise.ai",
    passwordHash: "$2a$10$w4f9G42u36wPZ7qL9iL1..O6j5dJc.dG0hYh13b2V9QY0a9u36wPZ", // Admin@123
    role: "ADMIN",
    phone: "+91 98400 12345",
    createdAt: new Date("2026-01-01T00:00:00Z").toISOString(),
    updatedAt: new Date("2026-01-01T00:00:00Z").toISOString(),
  },
  {
    id: "usr_driver_01",
    name: "Mohamed Thameem",
    email: "driver@voltwise.ai",
    passwordHash: "$2a$10$w4f9G42u36wPZ7qL9iL1..O6j5dJc.dG0hYh13b2V9QY0a9u36wPZ", // Driver@123
    role: "DRIVER",
    phone: "+91 98765 43210",
    createdAt: new Date("2026-01-10T00:00:00Z").toISOString(),
    updatedAt: new Date("2026-01-10T00:00:00Z").toISOString(),
  },
];

export const initialVehicles: Vehicle[] = [
  {
    id: "veh_nexon_01",
    userId: "usr_driver_01",
    make: "Tata",
    model: "Nexon EV Max (LR)",
    year: 2024,
    batteryCapacityKwh: 40.5,
    connectorType: "CCS2",
    apiSupported: true,
    obdSupported: true,
    connectionMode: "SIMULATION",
    currentBatteryPercentage: 23,
    estimatedRangeKm: 78,
    currentLatitude: 13.0382, // Near T. Nagar
    currentLongitude: 80.2458,
    chargingStatus: "IDLE",
    lastSyncedAt: new Date().toISOString(),
    createdAt: new Date("2026-02-01T10:00:00Z").toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "veh_ioniq_02",
    userId: "usr_driver_01",
    make: "Hyundai",
    model: "Ioniq 5 LR RWD",
    year: 2025,
    batteryCapacityKwh: 72.6,
    connectorType: "CCS2",
    apiSupported: true,
    obdSupported: true,
    connectionMode: "OEM_API",
    currentBatteryPercentage: 68,
    estimatedRangeKm: 310,
    currentLatitude: 13.0827,
    currentLongitude: 80.2707,
    chargingStatus: "IDLE",
    lastSyncedAt: new Date().toISOString(),
    createdAt: new Date("2026-02-15T12:00:00Z").toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export const initialStations: ChargingStation[] = [
  {
    id: "stn_zeon_ea",
    externalId: "OCM-IN-29481",
    name: "Zeon Charging — Express Avenue Mall",
    operator: "Zeon Electric",
    address: "Patullos Road, Royapettah, Basement Parking Level 2",
    city: "Chennai",
    state: "Tamil Nadu",
    country: "India",
    latitude: 13.0592,
    longitude: 80.2606,
    openingHours: "24/7",
    source: "OPEN_CHARGE_MAP",
    sourceId: "OCM-29481",
    sourceLastUpdated: new Date(Date.now() - 3600000).toISOString(),
    localLastUpdated: new Date(Date.now() - 120000).toISOString(),
    verificationStatus: "VERIFIED",
    createdAt: new Date("2026-01-01T00:00:00Z").toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "stn_tata_guindy",
    externalId: "BEE-TN-04812",
    name: "Tata Power EZ Charge — Olympia Tech Park",
    operator: "Tata Power",
    address: "1 SIDCO Industrial Estate, Guindy",
    city: "Chennai",
    state: "Tamil Nadu",
    country: "India",
    latitude: 13.0102,
    longitude: 80.2038,
    openingHours: "24/7",
    source: "BEE",
    sourceId: "BEE-04812",
    sourceLastUpdated: new Date(Date.now() - 7200000).toISOString(),
    localLastUpdated: new Date(Date.now() - 300000).toISOString(),
    verificationStatus: "VERIFIED",
    createdAt: new Date("2026-01-01T00:00:00Z").toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "stn_jiobp_velachery",
    externalId: "OCPI-JIO-7719",
    name: "Jio-bp pulse Hub — Phoenix Marketcity",
    operator: "Jio-bp pulse",
    address: "142 Velachery Main Road, Indira Gandhi Nagar",
    city: "Chennai",
    state: "Tamil Nadu",
    country: "India",
    latitude: 12.9916,
    longitude: 80.2170,
    openingHours: "24/7",
    source: "OCPI",
    sourceId: "JIO-7719",
    sourceLastUpdated: new Date(Date.now() - 1800000).toISOString(),
    localLastUpdated: new Date(Date.now() - 60000).toISOString(),
    verificationStatus: "VERIFIED",
    createdAt: new Date("2026-01-01T00:00:00Z").toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "stn_shell_omr",
    externalId: "OCPI-SHELL-901",
    name: "Shell Recharge Supercharger — Sholinganallur OMR",
    operator: "Shell Recharge",
    address: "Rajiv Gandhi Salai, Sholinganallur Junction",
    city: "Chennai",
    state: "Tamil Nadu",
    country: "India",
    latitude: 12.9010,
    longitude: 80.2279,
    openingHours: "24/7",
    source: "OCPI",
    sourceId: "SHELL-901",
    sourceLastUpdated: new Date(Date.now() - 900000).toISOString(),
    localLastUpdated: new Date(Date.now() - 45000).toISOString(),
    verificationStatus: "VERIFIED",
    createdAt: new Date("2026-01-01T00:00:00Z").toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "stn_relux_annanagar",
    externalId: "BEE-TN-09182",
    name: "Relux Electric — Anna Nagar West",
    operator: "Relux Electric",
    address: "2nd Avenue, Near Anna Nagar Roundtana",
    city: "Chennai",
    state: "Tamil Nadu",
    country: "India",
    latitude: 13.0850,
    longitude: 80.2101,
    openingHours: "24/7",
    source: "BEE",
    sourceId: "BEE-09182",
    sourceLastUpdated: new Date(Date.now() - 5400000).toISOString(),
    localLastUpdated: new Date(Date.now() - 240000).toISOString(),
    verificationStatus: "VERIFIED",
    createdAt: new Date("2026-01-01T00:00:00Z").toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "stn_fortum_tnagar",
    externalId: "OCM-IN-31089",
    name: "Fortum Charge & Drive — Pondy Bazaar T. Nagar",
    operator: "Fortum",
    address: "Thyagaraya Road, Near Multilevel Car Parking",
    city: "Chennai",
    state: "Tamil Nadu",
    country: "India",
    latitude: 13.0418,
    longitude: 80.2341,
    openingHours: "06:00 - 23:00",
    source: "OPEN_CHARGE_MAP",
    sourceId: "OCM-31089",
    sourceLastUpdated: new Date(Date.now() - 86400000).toISOString(),
    localLastUpdated: new Date(Date.now() - 600000).toISOString(),
    verificationStatus: "VERIFIED",
    createdAt: new Date("2026-01-01T00:00:00Z").toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "stn_ather_adyar",
    externalId: "LOCAL-ATH-001",
    name: "Ather Grid Fast Charger — Besant Nagar Beach",
    operator: "Ather Energy",
    address: "6th Avenue, Besant Nagar, Adyar",
    city: "Chennai",
    state: "Tamil Nadu",
    country: "India",
    latitude: 13.0001,
    longitude: 80.2667,
    openingHours: "24/7",
    source: "LOCAL",
    localLastUpdated: new Date().toISOString(),
    verificationStatus: "VERIFIED",
    createdAt: new Date("2026-01-01T00:00:00Z").toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "stn_highway_sriperumbudur",
    externalId: "OCPI-HWY-410",
    name: "Highway Express Ultra-Hub — Sriperumbudur",
    operator: "Zeon Electric",
    address: "NH48 Chennai-Bengaluru Highway, Sriperumbudur Toll Plaza",
    city: "Chennai Metro",
    state: "Tamil Nadu",
    country: "India",
    latitude: 12.9863,
    longitude: 79.9482,
    openingHours: "24/7",
    source: "OCPI",
    localLastUpdated: new Date().toISOString(),
    verificationStatus: "VERIFIED",
    createdAt: new Date("2026-01-01T00:00:00Z").toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export const initialChargers: Charger[] = [
  // Zeon EA
  { id: "chg_ea_01", stationId: "stn_zeon_ea", evseId: "ZEON-EA-01", connectorType: "CCS2", powerKw: 120, chargingType: "DC_ULTRA_FAST", status: "AVAILABLE", lastStatusUpdate: new Date().toISOString() },
  { id: "chg_ea_02", stationId: "stn_zeon_ea", evseId: "ZEON-EA-02", connectorType: "CCS2", powerKw: 120, chargingType: "DC_ULTRA_FAST", status: "OCCUPIED", lastStatusUpdate: new Date().toISOString() },
  { id: "chg_ea_03", stationId: "stn_zeon_ea", evseId: "ZEON-EA-03", connectorType: "CCS2", powerKw: 60, chargingType: "DC_FAST", status: "AVAILABLE", lastStatusUpdate: new Date().toISOString() },
  { id: "chg_ea_04", stationId: "stn_zeon_ea", evseId: "ZEON-EA-04", connectorType: "Type 2", powerKw: 22, chargingType: "AC_SLOW", status: "AVAILABLE", lastStatusUpdate: new Date().toISOString() },

  // Tata Guindy
  { id: "chg_guindy_01", stationId: "stn_tata_guindy", evseId: "TP-GU-01", connectorType: "CCS2", powerKw: 60, chargingType: "DC_FAST", status: "OCCUPIED", lastStatusUpdate: new Date().toISOString() },
  { id: "chg_guindy_02", stationId: "stn_tata_guindy", evseId: "TP-GU-02", connectorType: "CCS2", powerKw: 60, chargingType: "DC_FAST", status: "OCCUPIED", lastStatusUpdate: new Date().toISOString() },
  { id: "chg_guindy_03", stationId: "stn_tata_guindy", evseId: "TP-GU-03", connectorType: "Type 2", powerKw: 22, chargingType: "AC_SLOW", status: "AVAILABLE", lastStatusUpdate: new Date().toISOString() },

  // Jio-bp Velachery
  { id: "chg_jio_01", stationId: "stn_jiobp_velachery", evseId: "JIO-VEL-01", connectorType: "CCS2", powerKw: 150, chargingType: "DC_ULTRA_FAST", status: "AVAILABLE", lastStatusUpdate: new Date().toISOString() },
  { id: "chg_jio_02", stationId: "stn_jiobp_velachery", evseId: "JIO-VEL-02", connectorType: "CCS2", powerKw: 150, chargingType: "DC_ULTRA_FAST", status: "AVAILABLE", lastStatusUpdate: new Date().toISOString() },
  { id: "chg_jio_03", stationId: "stn_jiobp_velachery", evseId: "JIO-VEL-03", connectorType: "CCS2", powerKw: 60, chargingType: "DC_FAST", status: "OCCUPIED", lastStatusUpdate: new Date().toISOString() },
  { id: "chg_jio_04", stationId: "stn_jiobp_velachery", evseId: "JIO-VEL-04", connectorType: "Type 2", powerKw: 22, chargingType: "AC_SLOW", status: "AVAILABLE", lastStatusUpdate: new Date().toISOString() },

  // Shell OMR
  { id: "chg_shell_01", stationId: "stn_shell_omr", evseId: "SH-OMR-01", connectorType: "CCS2", powerKw: 120, chargingType: "DC_ULTRA_FAST", status: "AVAILABLE", lastStatusUpdate: new Date().toISOString() },
  { id: "chg_shell_02", stationId: "stn_shell_omr", evseId: "SH-OMR-02", connectorType: "CCS2", powerKw: 120, chargingType: "DC_ULTRA_FAST", status: "AVAILABLE", lastStatusUpdate: new Date().toISOString() },
  { id: "chg_shell_03", stationId: "stn_shell_omr", evseId: "SH-OMR-03", connectorType: "CCS2", powerKw: 50, chargingType: "DC_FAST", status: "AVAILABLE", lastStatusUpdate: new Date().toISOString() },

  // Relux Anna Nagar
  { id: "chg_relux_01", stationId: "stn_relux_annanagar", evseId: "REL-AN-01", connectorType: "CCS2", powerKw: 120, chargingType: "DC_ULTRA_FAST", status: "OCCUPIED", lastStatusUpdate: new Date().toISOString() },
  { id: "chg_relux_02", stationId: "stn_relux_annanagar", evseId: "REL-AN-02", connectorType: "CCS2", powerKw: 60, chargingType: "DC_FAST", status: "AVAILABLE", lastStatusUpdate: new Date().toISOString() },

  // Fortum T. Nagar
  { id: "chg_fortum_01", stationId: "stn_fortum_tnagar", evseId: "FOR-TN-01", connectorType: "CCS2", powerKw: 50, chargingType: "DC_FAST", status: "FAULTED", lastStatusUpdate: new Date().toISOString() },
  { id: "chg_fortum_02", stationId: "stn_fortum_tnagar", evseId: "FOR-TN-02", connectorType: "CHAdeMO", powerKw: 50, chargingType: "DC_FAST", status: "AVAILABLE", lastStatusUpdate: new Date().toISOString() },

  // Ather Adyar
  { id: "chg_ather_01", stationId: "stn_ather_adyar", evseId: "ATH-AD-01", connectorType: "Bharat AC-001", powerKw: 15, chargingType: "AC_SLOW", status: "AVAILABLE", lastStatusUpdate: new Date().toISOString() },

  // Sriperumbudur Highway
  { id: "chg_hwy_01", stationId: "stn_highway_sriperumbudur", evseId: "HWY-SRI-01", connectorType: "CCS2", powerKw: 150, chargingType: "DC_ULTRA_FAST", status: "AVAILABLE", lastStatusUpdate: new Date().toISOString() },
  { id: "chg_hwy_02", stationId: "stn_highway_sriperumbudur", evseId: "HWY-SRI-02", connectorType: "CCS2", powerKw: 150, chargingType: "DC_ULTRA_FAST", status: "AVAILABLE", lastStatusUpdate: new Date().toISOString() },
];

export const initialPrices: StationPrice[] = [
  { id: "prc_01", stationId: "stn_zeon_ea", pricingType: "PER_KWH", pricePerKwh: 18.5, sessionFee: 20, parkingFee: 30, currency: "INR", effectiveFrom: "2026-01-01T00:00:00Z" },
  { id: "prc_02", stationId: "stn_tata_guindy", pricingType: "PER_KWH", pricePerKwh: 19.0, sessionFee: 15, parkingFee: 0, currency: "INR", effectiveFrom: "2026-01-01T00:00:00Z" },
  { id: "prc_03", stationId: "stn_jiobp_velachery", pricingType: "PER_KWH", pricePerKwh: 17.5, sessionFee: 10, parkingFee: 40, currency: "INR", effectiveFrom: "2026-01-01T00:00:00Z" },
  { id: "prc_04", stationId: "stn_shell_omr", pricingType: "PER_KWH", pricePerKwh: 20.0, sessionFee: 25, parkingFee: 0, currency: "INR", effectiveFrom: "2026-01-01T00:00:00Z" },
  { id: "prc_05", stationId: "stn_relux_annanagar", pricingType: "PER_KWH", pricePerKwh: 18.0, sessionFee: 10, parkingFee: 20, currency: "INR", effectiveFrom: "2026-01-01T00:00:00Z" },
  { id: "prc_06", stationId: "stn_fortum_tnagar", pricingType: "PER_KWH", pricePerKwh: 19.5, sessionFee: 20, parkingFee: 50, currency: "INR", effectiveFrom: "2026-01-01T00:00:00Z" },
  { id: "prc_07", stationId: "stn_ather_adyar", pricingType: "PER_KWH", pricePerKwh: 12.0, sessionFee: 0, parkingFee: 0, currency: "INR", effectiveFrom: "2026-01-01T00:00:00Z" },
  { id: "prc_08", stationId: "stn_highway_sriperumbudur", pricingType: "PER_KWH", pricePerKwh: 21.0, sessionFee: 30, parkingFee: 0, currency: "INR", effectiveFrom: "2026-01-01T00:00:00Z" },
];

export const initialQueues: QueueEntry[] = [
  { id: "q_01", stationId: "stn_tata_guindy", vehicleId: "veh_ext_1", userId: "usr_guest_1", position: 1, estimatedWaitMinutes: 18, joinedAt: new Date(Date.now() - 600000).toISOString(), status: "WAITING" },
  { id: "q_02", stationId: "stn_tata_guindy", vehicleId: "veh_ext_2", userId: "usr_guest_2", position: 2, estimatedWaitMinutes: 32, joinedAt: new Date(Date.now() - 300000).toISOString(), status: "WAITING" },
  { id: "q_03", stationId: "stn_zeon_ea", vehicleId: "veh_ext_3", userId: "usr_guest_3", position: 1, estimatedWaitMinutes: 6, joinedAt: new Date(Date.now() - 120000).toISOString(), status: "WAITING" },
];

export const initialDemands: StationDemand[] = [
  { id: "dmd_01", stationId: "stn_zeon_ea", timestamp: new Date(Date.now() - 7200000).toISOString(), activeSessions: 2, availableChargers: 2, occupiedChargers: 2, queueLength: 1, utilizationPercentage: 50 },
  { id: "dmd_02", stationId: "stn_zeon_ea", timestamp: new Date().toISOString(), activeSessions: 1, availableChargers: 3, occupiedChargers: 1, queueLength: 1, utilizationPercentage: 25 },
  { id: "dmd_03", stationId: "stn_tata_guindy", timestamp: new Date(Date.now() - 7200000).toISOString(), activeSessions: 3, availableChargers: 0, occupiedChargers: 3, queueLength: 4, utilizationPercentage: 100 },
  { id: "dmd_04", stationId: "stn_tata_guindy", timestamp: new Date().toISOString(), activeSessions: 2, availableChargers: 1, occupiedChargers: 2, queueLength: 2, utilizationPercentage: 66.7 },
  { id: "dmd_05", stationId: "stn_jiobp_velachery", timestamp: new Date().toISOString(), activeSessions: 1, availableChargers: 3, occupiedChargers: 1, queueLength: 0, utilizationPercentage: 25 },
  { id: "dmd_06", stationId: "stn_shell_omr", timestamp: new Date().toISOString(), activeSessions: 0, availableChargers: 3, occupiedChargers: 0, queueLength: 0, utilizationPercentage: 0 },
];

export const initialReservations: Reservation[] = [
  {
    id: "res_01",
    userId: "usr_driver_01",
    vehicleId: "veh_nexon_01",
    stationId: "stn_jiobp_velachery",
    chargerId: "chg_jio_01",
    reservationStart: new Date(Date.now() + 3600000).toISOString(),
    reservationEnd: new Date(Date.now() + 6300000).toISOString(),
    status: "CONFIRMED",
    estimatedCost: 380,
    createdAt: new Date().toISOString(),
  },
];

export const initialFaultReports: FaultReport[] = [
  {
    id: "flt_01",
    userId: "usr_driver_01",
    stationId: "stn_fortum_tnagar",
    chargerId: "chg_fortum_01",
    category: "CONNECTOR_DAMAGED",
    description: "CCS2 gun lock pin broken; fails handshake with vehicle.",
    severity: "HIGH",
    status: "INVESTIGATING",
    createdAt: new Date(Date.now() - 86400000).toISOString(),
  },
];

export const initialNotifications: Notification[] = [
  {
    id: "ntf_01",
    userId: "usr_driver_01",
    title: "Battery Warning: Low State of Charge",
    message: "Tata Nexon EV battery is at 23% (78 km remaining). Intelligent charging recommendation ready.",
    type: "BATTERY_WARNING",
    read: false,
    createdAt: new Date(Date.now() - 1800000).toISOString(),
  },
  {
    id: "ntf_02",
    userId: "usr_driver_01",
    title: "Reservation Confirmed",
    message: "Charger reserved at Jio-bp pulse Velachery for 150 kW CCS2 port.",
    type: "RESERVATION",
    read: true,
    createdAt: new Date(Date.now() - 3600000).toISOString(),
  },
];

export const initialSyncLogs: StationSyncLog[] = [
  {
    id: "log_ocm_01",
    source: "OPEN_CHARGE_MAP",
    startedAt: new Date(Date.now() - 7200000).toISOString(),
    completedAt: new Date(Date.now() - 7180000).toISOString(),
    recordsReceived: 124,
    recordsCreated: 8,
    recordsUpdated: 42,
    recordsFailed: 0,
    status: "SUCCESS",
  },
  {
    id: "log_bee_01",
    source: "BEE",
    startedAt: new Date(Date.now() - 14400000).toISOString(),
    completedAt: new Date(Date.now() - 14370000).toISOString(),
    recordsReceived: 86,
    recordsCreated: 4,
    recordsUpdated: 31,
    recordsFailed: 1,
    status: "SUCCESS",
  },
  {
    id: "log_ocpi_01",
    source: "OCPI",
    startedAt: new Date(Date.now() - 1800000).toISOString(),
    completedAt: new Date(Date.now() - 1795000).toISOString(),
    recordsReceived: 45,
    recordsCreated: 2,
    recordsUpdated: 19,
    recordsFailed: 0,
    status: "SUCCESS",
  },
];
